name: ssscalc
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pip install -r requirements.txt
    http_port: 8080
    health_check:
      http_path: /healthz
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: PORT
        value: "8080"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PYTHONUNBUFFERED
        value: "1"
