name: ssscalc
services:
  - name: web
    environment_slug: python
    github:
      branch: main
      deploy_on_push: true
    run_command: gunicorn app:app --bind 0.0.0.0:8080 --workers 2 --timeout 120 --log-level info
    http_port: 8080
    health_check:
      http_path: /healthz
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: PORT
        value: "8080"
      - key: LOG_LEVEL
        value: "INFO"
